<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Cristiane Zhu e Júlia Zorzo Ferreira">

<title>Batalha dos Helicópteros 🚁</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Lançamento de helicópteros_files/libs/clipboard/clipboard.min.js"></script>
<script src="Lançamento de helicópteros_files/libs/quarto-html/quarto.js"></script>
<script src="Lançamento de helicópteros_files/libs/quarto-html/popper.min.js"></script>
<script src="Lançamento de helicópteros_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Lançamento de helicópteros_files/libs/quarto-html/anchor.min.js"></script>
<link href="Lançamento de helicópteros_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Lançamento de helicópteros_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Lançamento de helicópteros_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Lançamento de helicópteros_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Lançamento de helicópteros_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sumário</h2>
   
  <ul>
  <li><a href="#resumo" id="toc-resumo" class="nav-link active" data-scroll-target="#resumo"><span class="header-section-number">1</span> Resumo</a></li>
  <li><a href="#introdução" id="toc-introdução" class="nav-link" data-scroll-target="#introdução"><span class="header-section-number">2</span> Introdução</a></li>
  <li><a href="#materiais-e-métodos" id="toc-materiais-e-métodos" class="nav-link" data-scroll-target="#materiais-e-métodos"><span class="header-section-number">3</span> Materiais e Métodos</a>
  <ul class="collapse">
  <li><a href="#realização-do-experimento" id="toc-realização-do-experimento" class="nav-link" data-scroll-target="#realização-do-experimento"><span class="header-section-number">3.1</span> Realização do experimento</a></li>
  <li><a href="#escolha-dos-níveis-do-fator" id="toc-escolha-dos-níveis-do-fator" class="nav-link" data-scroll-target="#escolha-dos-níveis-do-fator"><span class="header-section-number">3.2</span> Escolha dos níveis do fator</a></li>
  <li><a href="#delineamento-utilizado" id="toc-delineamento-utilizado" class="nav-link" data-scroll-target="#delineamento-utilizado"><span class="header-section-number">3.3</span> Delineamento utilizado</a></li>
  <li><a href="#métodos-de-casualização" id="toc-métodos-de-casualização" class="nav-link" data-scroll-target="#métodos-de-casualização"><span class="header-section-number">3.4</span> Métodos de casualização</a></li>
  <li><a href="#constituíção-da-unidade-experimental" id="toc-constituíção-da-unidade-experimental" class="nav-link" data-scroll-target="#constituíção-da-unidade-experimental"><span class="header-section-number">3.5</span> Constituíção da unidade experimental</a></li>
  <li><a href="#aplicação-dos-tratamentos" id="toc-aplicação-dos-tratamentos" class="nav-link" data-scroll-target="#aplicação-dos-tratamentos"><span class="header-section-number">3.6</span> Aplicação dos tratamentos</a></li>
  <li><a href="#condições-de-condução-das-unidades-experimentais" id="toc-condições-de-condução-das-unidades-experimentais" class="nav-link" data-scroll-target="#condições-de-condução-das-unidades-experimentais"><span class="header-section-number">3.7</span> Condições de condução das unidades experimentais</a></li>
  <li><a href="#variável-resposta-medida" id="toc-variável-resposta-medida" class="nav-link" data-scroll-target="#variável-resposta-medida"><span class="header-section-number">3.8</span> Variável resposta medida</a></li>
  <li><a href="#tabela-dos-dados" id="toc-tabela-dos-dados" class="nav-link" data-scroll-target="#tabela-dos-dados"><span class="header-section-number">3.9</span> Tabela dos dados</a></li>
  <li><a href="#modelo-utilizado" id="toc-modelo-utilizado" class="nav-link" data-scroll-target="#modelo-utilizado"><span class="header-section-number">3.10</span> Modelo utilizado</a>
  <ul class="collapse">
  <li><a href="#delineamento-em-blocos-completos-inteiramente-casualizados." id="toc-delineamento-em-blocos-completos-inteiramente-casualizados." class="nav-link" data-scroll-target="#delineamento-em-blocos-completos-inteiramente-casualizados."><span class="header-section-number">3.10.1</span> Delineamento em blocos completos inteiramente casualizados.</a></li>
  </ul></li>
  <li><a href="#tabela-da-análise-de-variância" id="toc-tabela-da-análise-de-variância" class="nav-link" data-scroll-target="#tabela-da-análise-de-variância"><span class="header-section-number">3.11</span> Tabela da Análise de Variância</a>
  <ul class="collapse">
  <li><a href="#conclusões" id="toc-conclusões" class="nav-link" data-scroll-target="#conclusões"><span class="header-section-number">3.11.1</span> Conclusões</a></li>
  </ul></li>
  <li><a href="#testes-post-hoc" id="toc-testes-post-hoc" class="nav-link" data-scroll-target="#testes-post-hoc"><span class="header-section-number">3.12</span> Testes post-hoc</a>
  <ul class="collapse">
  <li><a href="#teste-de-tukey" id="toc-teste-de-tukey" class="nav-link" data-scroll-target="#teste-de-tukey"><span class="header-section-number">3.12.1</span> Teste de Tukey</a></li>
  <li><a href="#teste-de-student-newman-keuls" id="toc-teste-de-student-newman-keuls" class="nav-link" data-scroll-target="#teste-de-student-newman-keuls"><span class="header-section-number">3.12.2</span> Teste de Student-Newman-Keuls</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#resultados-e-discussão" id="toc-resultados-e-discussão" class="nav-link" data-scroll-target="#resultados-e-discussão"><span class="header-section-number">4</span> Resultados e Discussão</a>
  <ul class="collapse">
  <li><a href="#análise-exploratória" id="toc-análise-exploratória" class="nav-link" data-scroll-target="#análise-exploratória"><span class="header-section-number">4.1</span> Análise Exploratória</a>
  <ul class="collapse">
  <li><a href="#box-plots-dos-tempos-de-queda" id="toc-box-plots-dos-tempos-de-queda" class="nav-link" data-scroll-target="#box-plots-dos-tempos-de-queda"><span class="header-section-number">4.1.1</span> Box-plots dos tempos de queda</a></li>
  <li><a href="#gráfico-de-perfis" id="toc-gráfico-de-perfis" class="nav-link" data-scroll-target="#gráfico-de-perfis"><span class="header-section-number">4.1.2</span> Gráfico de perfis</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#ajuste-do-modelo" id="toc-ajuste-do-modelo" class="nav-link" data-scroll-target="#ajuste-do-modelo"><span class="header-section-number">5</span> Ajuste do Modelo</a>
  <ul class="collapse">
  <li><a href="#regressão-linear" id="toc-regressão-linear" class="nav-link" data-scroll-target="#regressão-linear"><span class="header-section-number">5.1</span> Regressão Linear</a></li>
  <li><a href="#significância-global-do-modelo" id="toc-significância-global-do-modelo" class="nav-link" data-scroll-target="#significância-global-do-modelo"><span class="header-section-number">5.2</span> Significância global do modelo</a></li>
  <li><a href="#aderência-do-modelo" id="toc-aderência-do-modelo" class="nav-link" data-scroll-target="#aderência-do-modelo"><span class="header-section-number">5.3</span> Aderência do modelo</a></li>
  <li><a href="#modelo-ajustado---equação" id="toc-modelo-ajustado---equação" class="nav-link" data-scroll-target="#modelo-ajustado---equação"><span class="header-section-number">5.4</span> Modelo ajustado - Equação</a>
  <ul class="collapse">
  <li><a href="#interpretação-dos-coeficientes" id="toc-interpretação-dos-coeficientes" class="nav-link" data-scroll-target="#interpretação-dos-coeficientes"><span class="header-section-number">5.4.1</span> Interpretação dos coeficientes</a></li>
  </ul></li>
  <li><a href="#anova-da-regressão" id="toc-anova-da-regressão" class="nav-link" data-scroll-target="#anova-da-regressão"><span class="header-section-number">5.5</span> ANOVA da Regressão</a></li>
  </ul></li>
  <li><a href="#análise-de-resíduos" id="toc-análise-de-resíduos" class="nav-link" data-scroll-target="#análise-de-resíduos"><span class="header-section-number">6</span> Análise de Resíduos</a>
  <ul class="collapse">
  <li><a href="#normalidade" id="toc-normalidade" class="nav-link" data-scroll-target="#normalidade"><span class="header-section-number">6.1</span> Normalidade</a>
  <ul class="collapse">
  <li><a href="#gráfico-q-q" id="toc-gráfico-q-q" class="nav-link" data-scroll-target="#gráfico-q-q"><span class="header-section-number">6.1.1</span> Gráfico Q-Q</a></li>
  </ul></li>
  <li><a href="#homocedasticidade-homogeneidade-de-variâncias" id="toc-homocedasticidade-homogeneidade-de-variâncias" class="nav-link" data-scroll-target="#homocedasticidade-homogeneidade-de-variâncias"><span class="header-section-number">6.2</span> Homocedasticidade: Homogeneidade de variâncias</a>
  <ul class="collapse">
  <li><a href="#testes-de-bartlett-e-levene" id="toc-testes-de-bartlett-e-levene" class="nav-link" data-scroll-target="#testes-de-bartlett-e-levene"><span class="header-section-number">6.2.1</span> Testes de Bartlett e Levene</a></li>
  </ul></li>
  <li><a href="#adequação-do-modelo-e-observações-discrepantes" id="toc-adequação-do-modelo-e-observações-discrepantes" class="nav-link" data-scroll-target="#adequação-do-modelo-e-observações-discrepantes"><span class="header-section-number">6.3</span> Adequação do modelo e observações discrepantes</a>
  <ul class="collapse">
  <li><a href="#outliers" id="toc-outliers" class="nav-link" data-scroll-target="#outliers"><span class="header-section-number">6.3.1</span> Outliers</a></li>
  <li><a href="#pontos-influentes" id="toc-pontos-influentes" class="nav-link" data-scroll-target="#pontos-influentes"><span class="header-section-number">6.3.2</span> Pontos influentes</a></li>
  <li><a href="#gráficos-de-diagnóstico" id="toc-gráficos-de-diagnóstico" class="nav-link" data-scroll-target="#gráficos-de-diagnóstico"><span class="header-section-number">6.3.3</span> Gráficos de Diagnóstico</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusões-1" id="toc-conclusões-1" class="nav-link" data-scroll-target="#conclusões-1"><span class="header-section-number">7</span> Conclusões</a>
  <ul class="collapse">
  <li><a href="#vídeo-da-realização-do-experimento" id="toc-vídeo-da-realização-do-experimento" class="nav-link" data-scroll-target="#vídeo-da-realização-do-experimento"><span class="header-section-number">7.1</span> Vídeo da realização do experimento</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Batalha dos Helicópteros 🚁</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Cristiane Zhu e Júlia Zorzo Ferreira </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="resumo" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Resumo</h1>
<p>Este trabalho investigou o efeito do comprimento da hélice no tempo de queda de helicópteros de papel por meio da utilização de um delineamento em blocos completos inteiramente casualizados com cinco tratamentos (3, 4, 5, 6 e 7cm de comprimento de hélice) e quatro blocos definidos pela gramatura do papel (35, 56, 75 e 120 g/m²). A ANOVA indicou efeito significativo do comprimento da hélice e da gramatura sobre o tempo de queda. Os testes post-hoc e o modelo de regressão linear ajustado confirmaram que hélices maiores resultam em também maiores tempos de queda, com aumento estimado de 278ms por centímetro adicional. Os pressupostos do modelo foram atendidos, com dois tempos identificados como pontos influentes de um total de vinte observações.</p>
</section>
<section id="introdução" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introdução</h1>
<p>Com motivação baseada na curiosidade em observar o comportamento de helicópteros de papel em queda livre, o objetivo desse experimento foi avaliar se o comprimento da hélice do helicóptero de papel influencia no seu tempo de queda. Porém, há uma fonte conhecida de variabilidade que pode influenciar no resultado: a gramatura do papel utilizada na execução dos helicópteros. Assim, foi necessária a utilização de um delineamento em blocos inteiramente casualizados (BIC).</p>
</section>
<section id="materiais-e-métodos" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Materiais e Métodos</h1>
<p>Para a realização do experimento foram utilizados: <br></p>
<p>5 tiras de papel de tamanho 3cm x 15cm com gramatura 35g/m² <br> 5 tiras de papel de tamanho 3cm x 15cm com gramatura 56g/m² <br> 5 tiras de papel de tamanho 3cm x 15cm com gramatura 75g/m² <br> 5 tiras de papel de tamanho 3cm x 15cm com gramatura 120g/m² <br> Lápis <br> Régua <br> Tesoura <br> Cronômetro <br> Escada doméstica</p>
<section id="realização-do-experimento" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="realização-do-experimento"><span class="header-section-number">3.1</span> Realização do experimento</h2>
<p>A fim de manter o controle local, uma mesma pessoa conduziu a queda de todos os helicópteros, da mesma forma e de uma mesma altura fixa, sendo inclusive a única a cronometrar o tempo de queda.</p>
<p>Não só isso, o experimento foi realizado em local fechado e idêntico para todos os lançamentos, num mesmo momento de um mesmo dia, sendo ele amplo o suficiente para que os helicópteros não tocassem outras superfícies que não o chão. A escolha da utilização de uma escada justifica-se pela tentativa de aumentar o tempo de queda de todos os helicópteros dado uma altura considerável para evitar imprecisões de marcação de tempo.</p>
</section>
<section id="escolha-dos-níveis-do-fator" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="escolha-dos-níveis-do-fator"><span class="header-section-number">3.2</span> Escolha dos níveis do fator</h2>
<p>Fator de tratamento: comprimento da hélice <br> Níveis: 3cm, 4cm, 5cm, 6cm, 7cm</p>
</section>
<section id="delineamento-utilizado" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="delineamento-utilizado"><span class="header-section-number">3.3</span> Delineamento utilizado</h2>
<p>Foi adotado o delineamento em blocos completos inteiramente casualizados, uma vez que o fator de interesse é o comprimento da hélice do helicóptero (tratamento), e há uma fonte conhecida de variabilidade, a gramatura do papel utilizado, que pode influenciar no tempo de queda. Dessa forma, a gramatura dos papéis foi considerada como bloco, permitindo controlar essa variabilidade (controle local) e aumentar a precisão na comparação entre os tratamentos.</p>
</section>
<section id="métodos-de-casualização" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="métodos-de-casualização"><span class="header-section-number">3.4</span> Métodos de casualização</h2>
<p>Foi realizado um sorteio para determinar a ordem dos blocos (definindo qual a gramatura de papel inicial, seguida das demais) e outro para estabelecer a ordem de aplicação dos tratamentos dentro de cada bloco (definindo a sequência de lançamento dos 5 helicópteros de hélices de tamanhos diferentes para cada gramatura de papel).</p>
</section>
<section id="constituíção-da-unidade-experimental" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="constituíção-da-unidade-experimental"><span class="header-section-number">3.5</span> Constituíção da unidade experimental</h2>
<p>A unidade experimental foi constituída por um helicóptero de papel individual, feito a partir de uma folha de papel 3cm x 15cm de gramatura específica e com um comprimento de hélice previamente definido. Cada helicóptero recebeu apenas um tratamento e foi submetido a um único lançamento para a obtenção da variável resposta.</p>
</section>
<section id="aplicação-dos-tratamentos" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="aplicação-dos-tratamentos"><span class="header-section-number">3.6</span> Aplicação dos tratamentos</h2>
<p>Os tratamentos foram aplicados durante a confecção dos helicópteros, por meio da variação do comprimento das hélices. Para isso, foram utilizados papéis 3 cm × 15 cm, sendo realizados cortes de modo a produzir helicópteros com comprimentos de hélice iguais a 3 cm, 4 cm, 5 cm, 6 cm e 7 cm, e mantendo constante as demais características da estrutura.</p>
</section>
<section id="condições-de-condução-das-unidades-experimentais" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="condições-de-condução-das-unidades-experimentais"><span class="header-section-number">3.7</span> Condições de condução das unidades experimentais</h2>
<p>Uma mesma pessoa realizou a confecção de todos os 20 helicópteros, de forma idêntica, desde o corte dos papéis até a utilização de um mesmo padrão de dobradura, garantindo a uniformidade do experimento.</p>
</section>
<section id="variável-resposta-medida" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="variável-resposta-medida"><span class="header-section-number">3.8</span> Variável resposta medida</h2>
<p>A variável resposta medida foi o tempo de queda do helicóptero, utilizando-se um cronômetro. O tempo foi tomado como a diferença entre o momento do primeiro toque do helicóptero no chão e o momento inicial em que o helicóptero se desprende da mão da pessoa que o segura. A unidade considerada para a análise foi milissegundos.</p>
</section>
<section id="tabela-dos-dados" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="tabela-dos-dados"><span class="header-section-number">3.9</span> Tabela dos dados</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tempo de queda dos helicópteros em milissegundos</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">3cm</th>
<th style="text-align: right;">4cm</th>
<th style="text-align: right;">5cm</th>
<th style="text-align: right;">6cm</th>
<th style="text-align: right;">7cm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">35g</td>
<td style="text-align: right;">2210</td>
<td style="text-align: right;">2680</td>
<td style="text-align: right;">3450</td>
<td style="text-align: right;">3460</td>
<td style="text-align: right;">3920</td>
</tr>
<tr class="even">
<td style="text-align: left;">56g</td>
<td style="text-align: right;">2310</td>
<td style="text-align: right;">2320</td>
<td style="text-align: right;">2340</td>
<td style="text-align: right;">2930</td>
<td style="text-align: right;">2840</td>
</tr>
<tr class="odd">
<td style="text-align: left;">75g</td>
<td style="text-align: right;">1910</td>
<td style="text-align: right;">2270</td>
<td style="text-align: right;">2620</td>
<td style="text-align: right;">2900</td>
<td style="text-align: right;">3770</td>
</tr>
<tr class="even">
<td style="text-align: left;">120g</td>
<td style="text-align: right;">1040</td>
<td style="text-align: right;">1590</td>
<td style="text-align: right;">1700</td>
<td style="text-align: right;">1810</td>
<td style="text-align: right;">1380</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="modelo-utilizado" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="modelo-utilizado"><span class="header-section-number">3.10</span> Modelo utilizado</h2>
<section id="delineamento-em-blocos-completos-inteiramente-casualizados." class="level3" data-number="3.10.1">
<h3 data-number="3.10.1" class="anchored" data-anchor-id="delineamento-em-blocos-completos-inteiramente-casualizados."><span class="header-section-number">3.10.1</span> Delineamento em blocos completos inteiramente casualizados.</h3>
<p>Para o experimento, foi utilizado o delineamento em blocos completos inteiramente casualizado (BIC) com cinco tratamentos e quatro blocos, pois há um fator de tratamento (comprimento da hélice) e uma fonte de variação que pode interferir no resultado mas que não deseja-se avaliar (gramatura do papel). Logo, o modelo matemático para o BIC é:</p>
<p><span class="math display">\[
Y_{ij} = \mu + \tau_i + \beta_j + \varepsilon_{ij}
\]</span> em que: <span class="math display">\[
\begin{aligned}
Y_{ij} &amp; = \text{observação do tratamento } i \text{ no bloco } j \\
\mu    &amp; = \text{média geral} \\
\tau_i &amp; = \text{efeito do tratamento } i \\
\beta_j &amp; = \text{efeito do bloco } j \\
\varepsilon_{ij} &amp; = \text{erro aleatório}
\end{aligned}
\]</span> Com as seguintes suposições a serem satisfeitas: <span class="math display">\[
\varepsilon_{ij} \sim N(0,\sigma^2)
\]</span></p>
<p><span class="math display">\[
\sum_{i=1}^{t}\tau_i = 0
\]</span> <span class="math display">\[
\sum_{j=1}^{b}\beta_j = 0
\]</span> Assim, são calculados os estimadores dos parâmetros como:</p>
<section id="média-geral" class="level4" data-number="3.10.1.1">
<h4 data-number="3.10.1.1" class="anchored" data-anchor-id="média-geral"><span class="header-section-number">3.10.1.1</span> Média geral</h4>
<p><span class="math display">\[
\hat{\mu} = \bar{Y}_{..}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>(mu <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">as.matrix</span>(tabela_dados)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2472.5</code></pre>
</div>
</div>
</section>
<section id="efeito-dos-tratamentos" class="level4" data-number="3.10.1.2">
<h4 data-number="3.10.1.2" class="anchored" data-anchor-id="efeito-dos-tratamentos"><span class="header-section-number">3.10.1.2</span> Efeito dos tratamentos</h4>
<p><span class="math display">\[
\hat{\tau}_j = \bar{Y}_{i.} - \bar{Y}_{..}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>media_individual <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(tabela_dados)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>tal <span class="ot">&lt;-</span> media_individual <span class="sc">-</span> mu</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>(estimativas <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Tratamento =</span> <span class="fu">c</span>(<span class="st">"3cm"</span>,<span class="st">"4cm"</span>,<span class="st">"5cm"</span>,<span class="st">"6cm"</span>, <span class="st">"7cm"</span>),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">Efeito_tratamento =</span> <span class="fu">round</span>(tal,<span class="dv">2</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">row.names =</span> <span class="cn">NULL</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tratamento Efeito_tratamento
1        3cm            -605.0
2        4cm            -257.5
3        5cm              55.0
4        6cm             302.5
5        7cm             505.0</code></pre>
</div>
</div>
</section>
<section id="efeito-dos-blocos" class="level4" data-number="3.10.1.3">
<h4 data-number="3.10.1.3" class="anchored" data-anchor-id="efeito-dos-blocos"><span class="header-section-number">3.10.1.3</span> Efeito dos blocos</h4>
<p><span class="math display">\[
\hat{\beta}_j = \bar{Y}_{j.} - \bar{Y}_{..}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>media_individual_b <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(tabela_dados)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> media_individual_b <span class="sc">-</span> mu</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>(estimativas_b <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Bloco =</span> <span class="fu">c</span>(<span class="st">"35g"</span>,<span class="st">"56g"</span>,<span class="st">"75g"</span>,<span class="st">"120g"</span>),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">Efeito_bloco =</span> <span class="fu">round</span>(beta,<span class="dv">2</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">row.names =</span> <span class="cn">NULL</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Bloco Efeito_bloco
1   35g        671.5
2   56g         75.5
3   75g        221.5
4  120g       -968.5</code></pre>
</div>
</div>
</section>
<section id="cálculos-dos-componentes-da-anova." class="level4" data-number="3.10.1.4">
<h4 data-number="3.10.1.4" class="anchored" data-anchor-id="cálculos-dos-componentes-da-anova."><span class="header-section-number">3.10.1.4</span> Cálculos dos componentes da ANOVA.</h4>
<p>Utilizando a ANOVA, realizou-se os testes de hipótese a seguir com significância de 5% e demais cálculos:</p>
<section id="hipóteses" class="level5" data-number="3.10.1.4.1">
<h5 data-number="3.10.1.4.1" class="anchored" data-anchor-id="hipóteses"><span class="header-section-number">3.10.1.4.1</span> Hipóteses</h5>
<p>Para efeito dos tratamentos: <br></p>
<p>H0: as médias dos tempos de queda dos helicópteros são iguais (em milissegundos). <br></p>
<p>H1: pelo menos uma das médias dos tempos de queda dos helicópteros é diferente (em milissegundos). <br></p>
<p><span class="math display">\[
H_0:\mu_1=\mu_2=\mu_3=\mu_4=\mu_5
\]</span></p>
<p><span class="math display">\[
H_1:\text{pelo menos uma média difere}
\]</span> Para efeito dos blocos: <br></p>
<p>H0: os efeitos das gramaturas de papel para a execução dos helicópteros são iguais a 0 . <br></p>
<p>H1: pelo menos um dos efeitos das grameturas de papel para a execução dos helicópteros é diferente de 0.</p>
<p><span class="math display">\[
H_0:\beta_1=\beta_2=\beta_3=\beta_4=0
\]</span></p>
<p><span class="math display">\[
H_1:\text{pelo menos um dos efeitos é diferente de 0}
\]</span></p>
</section>
<section id="graus-de-liberdade" class="level5" data-number="3.10.1.4.2">
<h5 data-number="3.10.1.4.2" class="anchored" data-anchor-id="graus-de-liberdade"><span class="header-section-number">3.10.1.4.2</span> Graus de liberdade</h5>
<p><span class="math display">\[
\begin{aligned}
t &amp; : \text{número de tratamentos}\\
b &amp; : \text{número de blocos}\\
n &amp; : \text{número total de observações}\\
N &amp; = t\times b
\\
GL_{trat} &amp; = t-1 : \text{graus de liberdade dos tratamentos}\\
GL_{bloco} &amp; = b-1 : \text{graus de liberdade dos blocos}\\
GL_{res} &amp; = (t - 1)(b - 1) :\text{graus de liberdade dos resíduos}\\
GL_{total} &amp; = N - 1: \text{graus de liberdade total}\\
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>n_trat <span class="ot">&lt;-</span> <span class="fu">ncol</span>(tabela_dados)   </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>n_bloco <span class="ot">&lt;-</span> <span class="fu">nrow</span>(tabela_dados)   </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> n_trat<span class="sc">*</span>n_bloco </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tratamento</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>(GL_trat <span class="ot">&lt;-</span> n_trat <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bloco</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>(GL_bloco <span class="ot">&lt;-</span> n_bloco <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># resíduos</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>(GL_res <span class="ot">&lt;-</span> (n_trat<span class="dv">-1</span>)<span class="sc">*</span>(n_bloco<span class="dv">-1</span>))    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># total</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>(GL_total <span class="ot">&lt;-</span> N <span class="sc">-</span> <span class="dv">1</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19</code></pre>
</div>
</div>
</section>
<section id="soma-de-quadrados" class="level5" data-number="3.10.1.4.3">
<h5 data-number="3.10.1.4.3" class="anchored" data-anchor-id="soma-de-quadrados"><span class="header-section-number">3.10.1.4.3</span> Soma de quadrados</h5>
<p>Soma de quadrados total <span class="math display">\[
SQ_{tot} = \sum_{i=1}^{t}\sum_{j=1}^{b}(Y_{ij}-\bar Y_{..})^2
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>(SQ_tot <span class="ot">&lt;-</span> <span class="fu">sum</span>((tabela_dados <span class="sc">-</span> mu)<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11854975</code></pre>
</div>
</div>
<p>Soma de quadrados dos tratamentos <span class="math display">\[
SQ_{trat} = b\sum_{i=1}^{t}(\bar Y_{i.}-\bar Y_{..})^2
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>(SQ_trat <span class="ot">&lt;-</span> n_bloco <span class="sc">*</span> <span class="fu">sum</span>((media_individual <span class="sc">-</span> mu)<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3127550</code></pre>
</div>
</div>
<p>Soma de quadrados dos blocos</p>
<p><span class="math display">\[
SQ_{trat} = t\sum_{i=1}^{b}(\bar Y_{.j}-\bar Y_{..})^2
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>(SQ_bloco <span class="ot">&lt;-</span> n_trat <span class="sc">*</span> <span class="fu">sum</span>((media_individual_b <span class="sc">-</span> mu)<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7218335</code></pre>
</div>
</div>
<p>Soma de quadrados dos resíduos</p>
<p><span class="math display">\[
SQ_{res} = SQ_{tot} - SQ_{trat} - SQ_{bloco}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>(SQ_res <span class="ot">&lt;-</span> SQ_tot <span class="sc">-</span> SQ_trat <span class="sc">-</span> SQ_bloco)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1509090</code></pre>
</div>
</div>
</section>
<section id="quadrados-médios" class="level5" data-number="3.10.1.4.4">
<h5 data-number="3.10.1.4.4" class="anchored" data-anchor-id="quadrados-médios"><span class="header-section-number">3.10.1.4.4</span> Quadrados médios</h5>
<p>Quadrado médio do tratamento</p>
<p><span class="math display">\[
QM_{trat} = \frac{SQ_{trat}}{t-1}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>(QM_trat <span class="ot">&lt;-</span> SQ_trat<span class="sc">/</span>GL_trat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 781887.5</code></pre>
</div>
</div>
<p>Quadrado médio do bloco</p>
<p><span class="math display">\[
QM_{bloco} = \frac{SQ_{bloco}}{b-1}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>(QM_bloco <span class="ot">&lt;-</span> SQ_bloco<span class="sc">/</span>GL_bloco)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2406112</code></pre>
</div>
</div>
<p>Quadrado médio do resíduo</p>
<p><span class="math display">\[
QM_{res} = \frac{SQ_res}{N-t}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>(QM_res <span class="ot">&lt;-</span> SQ_res<span class="sc">/</span>GL_res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 125757.5</code></pre>
</div>
</div>
</section>
<section id="estatística-de-teste-f" class="level5" data-number="3.10.1.4.5">
<h5 data-number="3.10.1.4.5" class="anchored" data-anchor-id="estatística-de-teste-f"><span class="header-section-number">3.10.1.4.5</span> Estatística de teste F</h5>
<p>Estatística de teste F para o tratamento <span class="math display">\[
F0 = \frac{QM_{Trat}}{QM_{res}}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>(F0 <span class="ot">&lt;-</span> QM_trat<span class="sc">/</span>QM_res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.217422</code></pre>
</div>
</div>
<p>Estatística de teste F para o bloco</p>
<p><span class="math display">\[
F0 = \frac{QM_{Bloco}}{QM_{res}}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>(F0b <span class="ot">&lt;-</span> QM_bloco<span class="sc">/</span>QM_res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19.13295</code></pre>
</div>
</div>
</section>
<section id="p-valor" class="level5" data-number="3.10.1.4.6">
<h5 data-number="3.10.1.4.6" class="anchored" data-anchor-id="p-valor"><span class="header-section-number">3.10.1.4.6</span> P-valor</h5>
<p>P-valor para o tratamento <span class="math display">\[
p-valor=P(F_{GL_{trat},GL_{res}} ≥F0)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(F0, GL_trat, GL_res))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.005999555</code></pre>
</div>
</div>
<p>P-valor para o bloco <span class="math display">\[
p-valor=P(F_{GL_{bloco},GL_{res} ≥F0)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(F0b, GL_bloco, GL_res))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.233719e-05</code></pre>
</div>
</div>
</section>
</section>
</section>
</section>
<section id="tabela-da-análise-de-variância" class="level2" data-number="3.11">
<h2 data-number="3.11" class="anchored" data-anchor-id="tabela-da-análise-de-variância"><span class="header-section-number">3.11</span> Tabela da Análise de Variância</h2>
<p>Apesar do cálculo de cada termo em separado, é possível calcular diretamente os resultados para a tabela da ANOVA:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>dados_anova <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">bloco =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">rownames</span>(dados), <span class="at">each =</span> <span class="fu">ncol</span>(dados))),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">tratamento =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">colnames</span>(dados), <span class="at">times =</span> <span class="fu">nrow</span>(dados))),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">tempo =</span> <span class="fu">as.vector</span>(base<span class="sc">::</span><span class="fu">t</span>(dados))</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(tempo <span class="sc">~</span> tratamento <span class="sc">+</span> bloco, dados_anova)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
tratamento   4 3127550  781888   6.217    0.006 ** 
bloco        3 7218335 2406112  19.133 7.23e-05 ***
Residuals   12 1509090  125758                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="conclusões" class="level3" data-number="3.11.1">
<h3 data-number="3.11.1" class="anchored" data-anchor-id="conclusões"><span class="header-section-number">3.11.1</span> Conclusões</h3>
<section id="teste-de-hipótese-do-tratamento" class="level4" data-number="3.11.1.1">
<h4 data-number="3.11.1.1" class="anchored" data-anchor-id="teste-de-hipótese-do-tratamento"><span class="header-section-number">3.11.1.1</span> Teste de hipótese do tratamento <br></h4>
<p>De modo a concluir o teste, após a construção da tabela ANOVA, verificamos o valor F0 do tratamento calculado, 6,22, em relação ao valor tabelado de F, dado por:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="dv">4</span>, <span class="dv">12</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.259167</code></pre>
</div>
</div>
<p>Com isso, é possível concluir que F0 &gt; F, já que 6,22 &gt; 3,26, rejeitando a hipótese nula ao nível de significância de 5%, isto é, há evidências de que pelo menos uma das médias é diferente das demais. Logo, há indícios de <strong>efeito significativo do comprimento da hélice sob o tempo de queda do helicóptero</strong>.</p>
</section>
<section id="teste-de-hipótese-do-bloco" class="level4" data-number="3.11.1.2">
<h4 data-number="3.11.1.2" class="anchored" data-anchor-id="teste-de-hipótese-do-bloco"><span class="header-section-number">3.11.1.2</span> Teste de hipótese do bloco <br></h4>
<p>Já para o bloco, o valor F0 do bloco calculado foi de 19,13, em relação ao valor tabelado de F, dado por:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="dv">3</span>, <span class="dv">12</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.490295</code></pre>
</div>
</div>
<p>Com isso, é possível concluir que F0 &gt; F, já que 19,13 &gt; 3,49, rejeitando a hipótese nula ao nível de significância de 5%, isto é, há evidências de que pelo menos um dos efeitos do bloco é diferente de zero. Logo, há indícios de efeito significativo da gramatura do papel sob o tempo de queda do helicóptero. Isto é, <strong>a blocagem pela gramatura foi eficaz</strong>.</p>
</section>
</section>
</section>
<section id="testes-post-hoc" class="level2" data-number="3.12">
<h2 data-number="3.12" class="anchored" data-anchor-id="testes-post-hoc"><span class="header-section-number">3.12</span> Testes post-hoc</h2>
<section id="teste-de-tukey" class="level3" data-number="3.12.1">
<h3 data-number="3.12.1" class="anchored" data-anchor-id="teste-de-tukey"><span class="header-section-number">3.12.1</span> Teste de Tukey</h3>
<p>O teste de comparações múltiplas de Tukey propõe identificar quais pares de tratamentos diferem entre si. Considera-se um nível de significância de 5%.</p>
<p>As hipóteses nulas, portanto, consistem na igualdade de médias par a par: <span class="math display">\[
H_0:μi−μi′=0
\]</span> Temos que as hipóteses alternativas são dadas por: <span class="math display">\[
H_1: \exists\, i \neq i' \text{ tal que } \mu_i \neq \mu_{i'}
\]</span></p>
<p>E a estatística de teste: <span class="math display">\[
q = \frac{\bar{Y}_{i.} - \bar{Y}_{i'.}}{\sqrt{QM_{res}/b}}
\]</span> O teste:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(anova, <span class="st">"tratamento"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = tempo ~ tratamento + bloco, data = dados_anova)

$tratamento
          diff       lwr      upr     p adj
4cm-3cm  347.5 -451.7689 1146.769 0.6472085
5cm-3cm  660.0 -139.2689 1459.269 0.1256203
6cm-3cm  907.5  108.2311 1706.769 0.0238824
7cm-3cm 1110.0  310.7311 1909.269 0.0060185
5cm-4cm  312.5 -486.7689 1111.769 0.7263335
6cm-4cm  560.0 -239.2689 1359.269 0.2320421
7cm-4cm  762.5  -36.7689 1561.769 0.0640700
6cm-5cm  247.5 -551.7689 1046.769 0.8561436
7cm-5cm  450.0 -349.2689 1249.269 0.4193449
7cm-6cm  202.5 -596.7689 1001.769 0.9233234</code></pre>
</div>
</div>
<p>Com isso, os resultados indicam que os pares 6cm–3cm (p = 0,024) e 7cm–3cm (p = 0,006) apresentaram diferença estatisticamente significativa. Ou seja, sugere-se que helicópteros com hélices de 6cm e 7cm possuem tempo de queda significativamente maior do que os com hélice de 3cm. Os demais pares não apresentaram evidências suficientes para rejeitar as médias iguais.</p>
</section>
<section id="teste-de-student-newman-keuls" class="level3" data-number="3.12.2">
<h3 data-number="3.12.2" class="anchored" data-anchor-id="teste-de-student-newman-keuls"><span class="header-section-number">3.12.2</span> Teste de Student-Newman-Keuls</h3>
<p>O teste de Student-Newman-Keuls (SNK) propõe agrupar os tratamentos em classes homogêneas, clusters, identificando quais diferem entre si. Considera-se novamente um nível de significância de 5%.</p>
<p>Da mesma forma, As hipóteses nulas consistem na igualdade de médias par a par: <span class="math display">\[
H_0: \mu_i - \mu_{i'} = 0
\]</span> E temos que as hipóteses alternativas são dadas por: <span class="math display">\[
H_1: \exists\, i \neq i' \text{ tal que } \mu_i \neq \mu_{i'}
\]</span> A estatística de teste: <span class="math display">\[
q = \frac{\bar{Y}_{i.} - \bar{Y}_{i'.}}{\sqrt{QM_{res}/b}}
\]</span> O teste:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>snk <span class="ot">&lt;-</span> <span class="fu">SNK.test</span>(anova, <span class="st">"tratamento"</span>, <span class="at">console =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Study: anova ~ "tratamento"

Student Newman Keuls Test
for tempo 

Mean Square Error:  125757.5 

tratamento,  means

     tempo       std r       se  Min  Max    Q25  Q50    Q75
3cm 1867.5  577.2564 4 177.3115 1040 2310 1692.5 2060 2235.0
4cm 2215.0  454.9359 4 177.3115 1590 2680 2100.0 2295 2410.0
5cm 2527.5  725.5975 4 177.3115 1700 3450 2180.0 2480 2827.5
6cm 2775.0  692.8444 4 177.3115 1810 3460 2627.5 2915 3062.5
7cm 2977.5 1167.2296 4 177.3115 1380 3920 2475.0 3305 3807.5

Alpha: 0.05 ; DF Error: 12 

Critical Range
       2        3        4        5 
546.3512 668.9838 744.4708 799.2689 

Means with the same letter are not significantly different.

     tempo groups
7cm 2977.5      a
6cm 2775.0     ab
5cm 2527.5    abc
4cm 2215.0     bc
3cm 1867.5      c</code></pre>
</div>
</div>
<p>Tabela de grupos:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Grupos homogêneos pelo teste SNK</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Tratamento</th>
<th style="text-align: right;">Média (ms)</th>
<th style="text-align: left;">Grupo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">7cm</td>
<td style="text-align: right;">2977.5</td>
<td style="text-align: left;">a</td>
</tr>
<tr class="even">
<td style="text-align: left;">6cm</td>
<td style="text-align: right;">2775.0</td>
<td style="text-align: left;">ab</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5cm</td>
<td style="text-align: right;">2527.5</td>
<td style="text-align: left;">abc</td>
</tr>
<tr class="even">
<td style="text-align: left;">4cm</td>
<td style="text-align: right;">2215.0</td>
<td style="text-align: left;">bc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3cm</td>
<td style="text-align: right;">1867.5</td>
<td style="text-align: left;">c</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Com isso, os resultados agruparam os tratamentos em classes homogêneas: hélices de 7cm e 6cm compõem o grupo de maior tempo de queda (grupo a), enquanto hélices de 4cm e 3cm formam o grupo de menor tempo (grupo c). O comprimento de 5cm ocupa posição intermediária, não diferindo significativamente de nenhum dos demais grupos. Assim como no teste anterior, de Tukey, há evidência de que hélices mais longas proporcionam maior tempo de queda.</p>
</section>
</section>
</section>
<section id="resultados-e-discussão" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Resultados e Discussão</h1>
<p>Os resultados indicaram que o comprimento da hélice influencia significativamente o tempo de queda do helicóptero. Em especial, helicópteros com hélices de 6cm e 7cm demoraram significativamente mais para chegar ao chão do que aqueles com hélices de 3cm, como esperado intuitivamente. A gramatura do papel também se mostrou relevante — papéis mais pesados resultaram em quedas mais rápidas, o que justificou a decisão de controlar esse fator no delineamento do experimento.</p>
<section id="análise-exploratória" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="análise-exploratória"><span class="header-section-number">4.1</span> Análise Exploratória</h2>
<section id="box-plots-dos-tempos-de-queda" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="box-plots-dos-tempos-de-queda"><span class="header-section-number">4.1.1</span> Box-plots dos tempos de queda</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>cores <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#2C3E7A"</span>, <span class="st">"#5B7DB1"</span>, <span class="st">"#9B2335"</span>, <span class="st">"#C96A75"</span>, <span class="st">"#C96A90"</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(tempo <span class="sc">~</span> tratamento,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> dados_anova,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Comprimento da hélice (cm)"</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Tempo de queda (ms)"</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Distribuição do tempo de queda por tratamento"</span>,</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> cores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lançamento-de-helicópteros_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O box-plot revela que, de modo geral, um maior tamanho de hélice possui um maior tempo de queda e também maior variabilidade.</p>
</section>
<section id="gráfico-de-perfis" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="gráfico-de-perfis"><span class="header-section-number">4.1.2</span> Gráfico de perfis</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(base<span class="sc">::</span><span class="fu">t</span>(dados),</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">"b"</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Comprimento da hélice (cm) - tratamento"</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Tempo de queda (ms)"</span>,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Tempo de queda por bloco e tratamento"</span>,</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">labels =</span> <span class="fu">colnames</span>(dados))</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">rownames</span>(dados),</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Gramatura"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lançamento-de-helicópteros_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico de perfis confirma a tendência de que o tempo de queda aumenta com o aumento comprimento da hélice, mas o cruzamento das retas — especialmente do bloco 120g — sugere uma possível interação entre comprimento e gramatura do helicóptero. De forma geral, papéis mais pesados apresentaram menores tempos de queda.</p>
<p>Com base somente na análise exploratória, imagina-se que os pressupostos do modelo serão satisfeitos.</p>
</section>
</section>
</section>
<section id="ajuste-do-modelo" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Ajuste do Modelo</h1>
<section id="regressão-linear" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="regressão-linear"><span class="header-section-number">5.1</span> Regressão Linear</h2>
<p>Foi ajustado um modelo de regressão linear relacionando o tempo de queda do helicóptero ao comprimento de sua hélice, incorporando o efeito dos blocos (gramatura).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>dados_reg <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">bloco =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">rownames</span>(dados), <span class="at">each =</span> <span class="fu">ncol</span>(dados))),</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">comprimento =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>), <span class="at">times =</span> <span class="fu">nrow</span>(dados)),</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">tempo =</span> <span class="fu">as.vector</span>(base<span class="sc">::</span><span class="fu">t</span>(dados))</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>modelo_linear <span class="ot">&lt;-</span> <span class="fu">lm</span>(tempo <span class="sc">~</span> comprimento <span class="sc">+</span> bloco, <span class="at">data =</span> dados_reg)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>resumo <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo_linear)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>resumo</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tempo ~ comprimento + bloco, data = dados_reg)

Residuals:
   Min     1Q Median     3Q    Max 
-680.0 -191.5   33.0  202.0  520.0 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   114.00     291.53   0.391  0.70127    
comprimento   278.00      50.75   5.478 6.36e-05 ***
bloco35g     1640.00     203.00   8.079 7.63e-07 ***
bloco56g     1044.00     203.00   5.143  0.00012 ***
bloco75g     1190.00     203.00   5.862 3.12e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 321 on 15 degrees of freedom
Multiple R-squared:  0.8697,    Adjusted R-squared:  0.8349 
F-statistic: 25.02 on 4 and 15 DF,  p-value: 1.736e-06</code></pre>
</div>
</div>
<p>O modelo apresentou erro padrão residual de 321ms, indicando a variabilidade média dos resíduos em torno dos valores ajustados. Todos os coeficientes, exceto o intercepto (p = 0,70), foram estatisticamente significativos ao nível de 5%.</p>
</section>
<section id="significância-global-do-modelo" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="significância-global-do-modelo"><span class="header-section-number">5.2</span> Significância global do modelo</h2>
<p>A significância global foi avaliada pelo teste F. O p-valor muito inferior a 0,05 indica que o modelo é <strong>globalmente significativo</strong>, ou seja, pelo menos o comprimento ou a gramatura contribuem para explicar o tempo de queda.</p>
</section>
<section id="aderência-do-modelo" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="aderência-do-modelo"><span class="header-section-number">5.3</span> Aderência do modelo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>resumo<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8696513</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>resumo<span class="sc">$</span>adj.r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8348917</code></pre>
</div>
</div>
<p>O R² de 0,8696 indica que aproximadamente 87% da variabilidade observada no tempo de queda é explicada pelo modelo. O R² ajustado de 0,8349 confirma a boa aderência mesmo após penalizar pelo número de parâmetros estimados.</p>
</section>
<section id="modelo-ajustado---equação" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="modelo-ajustado---equação"><span class="header-section-number">5.4</span> Modelo ajustado - Equação</h2>
<p><span class="math display">\[
\hat{Y} = 114 + 278 \times \text{Comprimento} + 1640 \times I_{35g} + 1044 \times I_{56g} + 1190 \times I_{75g}
\]</span></p>
<section id="interpretação-dos-coeficientes" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="interpretação-dos-coeficientes"><span class="header-section-number">5.4.1</span> Interpretação dos coeficientes</h3>
<p>Para cada aumento de 1 cm no comprimento da hélice, o tempo médio de queda aumenta aproximadamente 278 ms, mantendo-se constante a gramatura. Além disso, para um mesmo comprimento de hélice, papéis de 35g resultam em tempos 1640 ms maiores, 56g em 1044 ms maiores e 75g em 1190 ms maiores. O intercepto de 114 ms representa o tempo esperado para comprimento zero no bloco de referência (120g), sem interpretação direta.</p>
</section>
</section>
<section id="anova-da-regressão" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="anova-da-regressão"><span class="header-section-number">5.5</span> ANOVA da Regressão</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo_linear)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: tempo
            Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
comprimento  1 3091360 3091360  30.008 6.363e-05 ***
bloco        3 7218335 2406112  23.356 6.629e-06 ***
Residuals   15 1545280  103019                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>A tabela ANOVA da regressão indica efeito significativo tanto do comprimento da hélice (tratamento - p &lt; 0,001) quanto da gramatura do papel (p &lt; 0,001). Portanto, ambas as variáveis contribuem significativamente para explicar o tempo de queda dos helicópteros.</p>
</section>
</section>
<section id="análise-de-resíduos" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Análise de Resíduos</h1>
<section id="normalidade" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="normalidade"><span class="header-section-number">6.1</span> Normalidade</h2>
<p>A verificação da suposição de normalidade foi feita pelo teste de Shapiro-Wilk, adequado para amostras pequenas. Hipóteses: <span class="math display">\[
H_0:\ \varepsilon_{ij} \sim N(0,\sigma^2)
\]</span> <span class="math display">\[
H_1:\ \varepsilon_{ij} \not\sim N(0,\sigma^2)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(modelo_linear))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(modelo_linear)
W = 0.98306, p-value = 0.9672</code></pre>
</div>
</div>
<p>Com p-valor de 0,9672, não há evidências de violação da normalidade dos resíduos ao nível de 5%.</p>
<section id="gráfico-q-q" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="gráfico-q-q"><span class="header-section-number">6.1.1</span> Gráfico Q-Q</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(modelo_linear),</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">"Gráfico Q-Q dos resíduos"</span>,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Quantis teóricos"</span>,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Quantis amostrais dos resíduos"</span>,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"#9B2335"</span>)</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">residuals</span>(modelo_linear), <span class="at">col =</span> <span class="st">"#535353"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lançamento-de-helicópteros_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Os pontos se distribuem próximos à reta, com dois pontos nas extremidades sugerindo possíveis outliers, mas sem comprometer a suposição de normalidade.</p>
</section>
</section>
<section id="homocedasticidade-homogeneidade-de-variâncias" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="homocedasticidade-homogeneidade-de-variâncias"><span class="header-section-number">6.2</span> Homocedasticidade: Homogeneidade de variâncias</h2>
<section id="testes-de-bartlett-e-levene" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="testes-de-bartlett-e-levene"><span class="header-section-number">6.2.1</span> Testes de Bartlett e Levene</h3>
<p><span class="math display">\[
H_0:\sigma_1^2=\sigma_2^2=\sigma_3^2=\sigma_4^2=\sigma_5^2
\]</span> <span class="math display">\[
H_1:\text{ pelo menos um } \sigma_i^2 \neq \sigma_j^2
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(<span class="fu">residuals</span>(modelo_linear) <span class="sc">~</span> dados_reg<span class="sc">$</span>bloco)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  residuals(modelo_linear) by dados_reg$bloco
Bartlett's K-squared = 1.0609, df = 3, p-value = 0.7865</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: carData</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(tempo <span class="sc">~</span> bloco, <span class="at">data =</span> dados_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  3  0.8381 0.4926
      16               </code></pre>
</div>
</div>
<p>Ambos os testes não rejeitam a hipótese de homogeneidade de variâncias ao nível de 5% — Bartlett (p = 0,79) e Levene (p = 0,49) — confirmando a suposição de homocedasticidade.</p>
</section>
</section>
<section id="adequação-do-modelo-e-observações-discrepantes" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="adequação-do-modelo-e-observações-discrepantes"><span class="header-section-number">6.3</span> Adequação do modelo e observações discrepantes</h2>
<section id="outliers" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="outliers"><span class="header-section-number">6.3.1</span> Outliers</h3>
<p>Toma-se os resíduos padronizados que estão a mais de 2 desvios padrão da média como aqueles correspondentes aos outliers, dado que, em uma distribuição normal, isso corresponde a aproximadamente 5% do total das observações. <span class="math display">\[
∣r_i​∣&gt;2
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>(outliers <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">abs</span>(<span class="fu">rstandard</span>(modelo_linear)) <span class="sc">&gt;</span> <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>20 
20 </code></pre>
</div>
</div>
<p>A observação 20 é outlier. Mas essa informação pode ser complementada com o fato do tempo ser influente, ou não, além de outlier. Verifica-se abaixo.</p>
</section>
<section id="pontos-influentes" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="pontos-influentes"><span class="header-section-number">6.3.2</span> Pontos influentes</h3>
<p>Toma-se a distância de Cook como medida de influência de cada observação sobre o ajuste do modelo, onde n é o número de observações e p o número de parâmetros estimados. <span class="math display">\[
D_i &gt; \frac{4}{n-p}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dados_reg)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coef</span>(modelo_linear))</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>(influentes <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">cooks.distance</span>(modelo_linear) <span class="sc">&gt;</span> <span class="dv">4</span> <span class="sc">/</span> (n <span class="sc">-</span> p)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>15 20 
15 20 </code></pre>
</div>
</div>
<p>As observações 15 e 20 foram identificadas como pontos influentes, ou seja, sua remoção alteraria de forma relevante o ajuste do modelo. Coincidentemente, a observação 20 também foi identificada como outlier, sendo portanto tanto discrepante quanto influente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>dados_reg[influentes, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   bloco comprimento tempo
15   75g           7  3770
20  120g           7  1380</code></pre>
</div>
</div>
<p>As observações 15 e 20 correspondem, respectivamente, aos helicópteros de gramatura 75g e 120g com hélice de 7cm. A observação 20 apresentou tempo de queda de 1380ms, valor baixo para uma hélice de 7cm e que contraria a tendência geral de que hélices maiores resultam em maiores tempos de queda. A observação 15, por sua vez, apresentou o maior tempo registrado no experimento (3770ms). Ambas fogem do padrão geral dos dados, o que justifica sua identificação como pontos influentes.</p>
</section>
<section id="gráficos-de-diagnóstico" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="gráficos-de-diagnóstico"><span class="header-section-number">6.3.3</span> Gráficos de Diagnóstico</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_linear)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lançamento-de-helicópteros_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Os gráficos de diagnóstico do modelo indicam adequação geral do ajuste. O gráfico de Resíduos vs Ajustados não apresenta padrão sistemático, sem evidências de não linearidade. O gráfico Scale-Location confirma a homocedasticidade, com linha aproximadamente horizontal. O gráfico Q-Q reforça a normalidade dos resíduos. No gráfico de alavancagem, as observações 15 e 20 se destacam e, de fato, são confirmadas como pontos influentes.</p>
</section>
</section>
</section>
<section id="conclusões-1" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusões</h1>
<p>O experimento demonstrou como principais evidências: <strong>o comprimento da hélice influencia significativamente o tempo de queda do helicóptero de papel</strong>. A ANOVA indica efeito significativo do tratamento (p = 0,006), e os testes post-hoc de Tukey e SNK apontam que hélices de 6cm e 7cm resultam em tempos de queda significativamente maiores do que hélices de 3cm. Não só isso, o modelo de regressão linear ajustado confirma essa tendência e estimando um aumento médio de 278ms no tempo de queda para cada centímetro adicional no comprimento da hélice. A gramatura do papel também se mostra relevante (p &lt; 0,001), com papéis mais leves resultando em quedas mais lentas, o que justifica a adoção do delineamento em blocos. Os pressupostos do modelo foram atendidos, com exceção da presença das observações 15 e 20, identificadas como pontos influentes, sendo a observação 20 também um outlier — ambas referentes a helicópteros com hélice de 7cm.</p>
<section id="vídeo-da-realização-do-experimento" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="vídeo-da-realização-do-experimento"><span class="header-section-number">7.1</span> Vídeo da realização do experimento</h2>
<p><a href="https://youtu.be/_ppstvdEkbc">Batalha dos Helicópteros - YouTube</a></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="Lançamento de helicópteros_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>
